name: Git Tag
on:
 pull_request:
   branches:
     - main
   types:
     - closed
jobs:
 main:
   runs-on: ubuntu-latest
   if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-')
   steps:
     - uses: actions/checkout@v2
     - run: git fetch origin ${{ github.base_ref }}
     - run: git checkout ${{ github.base_ref }}
     - run: git tag `echo '${{ github.base_ref }}' | sed 's/release-/v/'`
     - run: git push origin `echo '${{ github.base_ref }}' | sed 's/release-/v/'`
