name: Git Tag
on:
 pull_request:
   branches:
     - master
   types:
     - closed
jobs:
 main:
   runs-on: ubuntu-latest
   if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-')
   steps:
     - uses: actions/checkout@v2
     - run: git fetch origin ${{ github.event.pull_request.head.ref }}
     - run: echo '${{ github.event.pull_request.head.ref }}' | sed 's/release-/v/' > TAG_NAME
     - run: git checkout ${{ github.base_ref }}
     - run: git tag $(cat TAG_NAME)
     - run: git push origin $(cat TAG_NAME)

